
package it.cedaf.authservice.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2024-05-30T10:28:47.433+02:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "fault", targetNamespace = "http://service.authservice.cedaf.it")
public class AuthException_Exception extends Exception {

    private it.cedaf.authservice.service.AuthException fault;

    public AuthException_Exception() {
        super();
    }

    public AuthException_Exception(String message) {
        super(message);
    }

    public AuthException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AuthException_Exception(String message, it.cedaf.authservice.service.AuthException fault) {
        super(message);
        this.fault = fault;
    }

    public AuthException_Exception(String message, it.cedaf.authservice.service.AuthException fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public it.cedaf.authservice.service.AuthException getFaultInfo() {
        return this.fault;
    }
}
